services:
  receipt-processor:
    container_name: receipt-processor
    build:
      context: .
      dockerfile: Dockerfile
    image: receipt-processor:latest
    ports:
      - "1313:1313"
    command: go run point_calculation_logic.go main.go
